name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Heroku
        if: job.status == 'success'
        run: |
          rm -rf .git
          cd ..
          mkdir heroku
          cd heroku
          git clone https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/doi-cite.git
          cd doi-cite
          find . -maxdepth 1 ! -path './.git' ! -path '.' -exec rm -rf {} +
          git config --global user.email "${{ secrets.HEROKU_DEPLOY_EMAIL }}"
          git config --global user.name "${{ secrets.HEROKU_DEPLOY_NAME }}"
          git commit . -m "Cleaned old version"
          cd ../..
          cp -rT ./doi-cite ./heroku/doi-cite
          cd ./heroku/doi-cite
          git add .
          git commit . -m "Deploy new version from ${{ github.ref }}"
          git push
